package de.vatrascell.nezr.message;

public enum DialogId implements AbstractId {

    TITLE_COPY_QUESTIONNAIRE,
    TITLE_RENAME_QUESTIONNAIRE,
    TITLE_REMOVE_QUESTIONNAIRE,
    TITLE_CREATE_QUESTIONNAIRE,
    TITLE_EXCEL_EXPORT,
    TITLE_CREATE_ANSWER,
    TITLE_CREATE_CATEGORY,
    TITLE_CREATE_HEADLINE,

    HEADER_TEXT_COPY_QUESTIONNAIRE,
    HEADER_TEXT_REMOVE_QUESTIONNAIRE,

    CONTENT_TEXT_COPY_QUESTIONNAIRE,
    CONTENT_TEXT_RENAME_QUESTIONNAIRE,
    CONTENT_TEXT_REMOVE_QUESTIONNAIRE,
    CONTENT_TEXT_CREATE_QUESTIONNAIRE,
    CONTENT_TEXT_CREATE_ANSWER,
    CONTENT_TEXT_CREATE_CATEGORY,
    CONTENT_TEXT_CREATE_HEADLINE,

    BUTTON_EXCEL_EXPORT,

    DATEPICKER_EXPORT_FROM,
    DATEPICKER_EXPORT_TO,

    DATEPICKER_EXPORT_FROM_LABEL,
    DATEPICKER_EXPORT_TO_LABEL
}
