package message;

public enum MessageId implements AbstractId {

    TITLE_UNDEFINED,
    TITLE_CREATE_CATEGORY,
    TITLE_LOGIN,
    TITLE_COPY_QUESTIONNAIRE,
    TITLE_EXCEL_EXPORT,
    TITLE_REMOVE_QUESTIONNAIRE,

    MESSAGE_CATEGORY_ALREADY_EXISTS,
    MESSAGE_CATEGORY_CREATED_SUCCESSFULLY,
    MESSAGE_LOGIN_WRONG_DATA,
    MESSAGE_COPYED_QUESTIONNAIRE_SUCCESSFULLY,
    MESSAGE_EXPORTED_QUESTIONNAIRE_SUCCESSFULLY,
    MESSAGE_DELETED_QUESTIONNAIRE_SUCCESSFULLY,
    MESSAGE_UNDEFINED_ERROR
}
