package message;

public enum MessageId implements AbstractId {

    TITLE_UNDEFINED,
    TITLE_CREATE_CATEGORY,
    TITLE_LOGIN,
    TITLE_COPY_QUESTIONNAIRE,
    TITLE_EXCEL_EXPORT,
    TITLE_REMOVE_QUESTIONNAIRE,
    TITLE_SAVE_QUESTION,
    TITLE_CREATE_ANSWER,
    TITLE_CREATE_HEADLINE,

    MESSAGE_CATEGORY_ALREADY_EXISTS,
    MESSAGE_CATEGORY_CREATED_SUCCESSFULLY,
    MESSAGE_LOGIN_WRONG_DATA,
    MESSAGE_COPYED_QUESTIONNAIRE_SUCCESSFULLY,
    MESSAGE_EXPORTED_QUESTIONNAIRE_SUCCESSFULLY,
    MESSAGE_DELETED_QUESTIONNAIRE_SUCCESSFULLY,
    MESSAGE_UNDEFINED_ERROR,
    MESSAGE_SAVE_QUESTION_ERROR,
    MESSAGE_SAVE_QUESTION_ALREADY_EXISTS_ERROR,
    MESSAGE_CREATE_ANSWER,
    MESSAGE_CREATE_HEADLINE,
    MESSAGE_CATEGORY_HEADLINE_EXISTS,
}
