package message;

public enum MessageId {

    TITLE_CREATE_CATEGORY,
    TITLE_LOGIN,

    MESSAGE_CATEGORY_ALREADY_EXISTS,
    MESSAGE_CATEGORY_CREATED_SUCCESSFULLY,
    MESSAGE_LOGIN_WRONG_DATA,
    MESSAGE_UNDEFINED_ERROR;
}
